name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Generate index readme
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: |
           npm i docsify-cli -g
           rm README.md
           docsify generate . --sidebar README.md
           python3 ./github/add_header.py
           mv README_tmp.md README.md
           git config --global user.email "lqs@mail.bnu.edu.cn"
           git config --global user.name "Qingsong Lv"
           git add README.md
           git commit -m "index file by github actions"
           git push origin docs
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."


